name: To Epitech Github

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  to_epitech:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to Epitech Github
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:EpitechPromo2025/B-YEP-400-RUN-4-1-indiestudio-alwyn.mattapullut.git
          ssh_private_key:
            ${{ secrets.SSH_TO_EPITECH }}
